# pick our container
sudo: false
dist: trusty

# pick our language/runtime
language: python
python: '3.5'

# install our deps
install: pip3 install --user -r requirements.txt

# check for changes
script:
  # fetch the dictionary pages
  - bin/fetch.py

# submit the changes
after_success:
  -|
    if ! [[ -n "$(git status --porcelain)" ]]; then
      bin/snitch.py "no changes"
    else
      bin/submit-pr.py
      bin/snitch.py "changes happened"
    fi
